import Head from "next/head";
import Image from "next/image";
import { Navbar, Header, HowItWork, AboutUs, Services, Contact, Footer } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HowItWork />
      <AboutUs />
      <Services />
      <Contact />
    </div>
  );
}
